# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SA-WeatherApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#pod 'APIManager-New', :git => 'git@github.com:ptejas26/APIManager-New.git'
#No more using my own git

pod 'APIManager-New', '~> 0.1.2'
end
